export enum TypeUser {
  ALUNO = 'ALUNO',
  SERVIDOR = 'SERVIDOR',
  EXTERNO = 'EXTERNO',
}

export enum FunctionServer {
  PROFESSOR_EDUCACAO_FISICA = 'PROFESSOR_EDUCACAO_FISICA',
  PROFESSOR_OUTROS = 'PROFESSOR_OUTROS',
  DIRETOR = 'DIRETOR',
  COORDENADOR = 'COORDENADOR',
  OUTRO = 'OUTRO',
}
